export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_CARI_LIST_START = "GET_CARI_LIST_START";
export const GET_CARI_LIST_FAIL = "GET_CARI_LIST_FAIL";
export const GET_CARI_LIST_SUCCESS = "GET_CARI_LIST_SUCCESS";

export const GET_CARI_DETAY_START = "GET_CARI_DETAY_START";
export const GET_CARI_DETAY_FAIL = "GET_CARI_DETAY_FAIL";
export const GET_CARI_DETAY_SUCCESS = "GET_CARI_DETAY_SUCCESS";

export const CARI_EKLE_START = "CARI_EKLE_START";
export const CARI_EKLE_FAIL = "CARI_EKLE_FAIL";
export const CARI_EKLE_SUCCESS = "CARI_EKLE_SUCCESS";

export const GET_STOK_LIST_START = "GET_STOK_LIST_START";
export const GET_STOK_LIST_FAIL = "GET_STOK_LIST_FAIL";
export const GET_STOK_LIST_SUCCESS = "GET_STOK_LIST_SUCCESS";

export const GET_STOK_DETAY_START = "GET_STOK_DETAY_START";
export const GET_STOK_DETAY_FAIL = "GET_STOK_DETAY_FAIL";
export const GET_STOK_DETAY_SUCCESS = "GET_STOK_DETAY_SUCCESS";

export const STOK_EKLE_START = "STOK_EKLE_START";
export const STOK_EKLE_FAIL = "STOK_EKLE_FAIL";
export const STOK_EKLE_SUCCESS = "STOK_EKLE_SUCCESS";

export const PATCH_ARAC_RESIMLERI_START = "PATCH_ARAC_RESIMLERI_START";
export const PATCH_ARAC_RESIMLERI_FAIL = "PATCH_ARAC_RESIMLERI_FAIL";
export const PATCH_ARAC_RESIMLERI_SUCCESS = "PATCH_ARAC_RESIMLERI_SUCCESS";

export const PATCH_RUHSAT_RESIMLERI_START = "PATCH_RUHSAT_RESIMLERI_START";
export const PATCH_RUHSAT_RESIMLERI_FAIL = "PATCH_RUHSAT_RESIMLERI_FAIL";
export const PATCH_RUHSAT_RESIMLERI_SUCCESS = "PATCH_RUHSAT_RESIMLERI_SUCCESS";
