# Generated by Django 2.2.3 on 2019-12-02 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191202_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cariler',
            name='added_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
