# Generated by Django 2.2.3 on 2019-12-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stoklar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoklar',
            old_name='alisfiyati',
            new_name='alis_fiyati',
        ),
        migrations.RenameField(
            model_name='stoklar',
            old_name='alistarihi',
            new_name='alis_tarihi',
        ),
        migrations.RenameField(
            model_name='stoklar',
            old_name='aracresimleri',
            new_name='arac_resimleri',
        ),
        migrations.RenameField(
            model_name='stoklar',
            old_name='motorno',
            new_name='motor_no',
        ),
        migrations.RenameField(
            model_name='stoklar',
            old_name='ruhsatno',
            new_name='ruhsat_no',
        ),
        migrations.RenameField(
            model_name='stoklar',
            old_name='ruhsatresimleri',
            new_name='ruhsat_resimleri',
        ),
        migrations.RenameField(
            model_name='stoklar',
            old_name='saseno',
            new_name='sase_no',
        ),
    ]
