# Generated by Django 2.2.3 on 2019-12-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191202_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoklar',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoklar',
            name='tur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
