# Generated by Django 2.2.3 on 2019-12-03 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191203_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cariler',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stoklar',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stok_added_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
