# Generated by Django 2.2.4 on 2019-12-04 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20191203_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoklar',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stoklar_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AracResimleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='aracresimleri')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aracresimleri_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
