# Generated by Django 2.2.4 on 2019-12-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191204_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aracresimleri',
            name='name',
        ),
    ]
