# Generated by Django 2.2.4 on 2019-12-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_aracresimleri_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoklar',
            name='arac_resimleri',
            field=models.ImageField(blank=True, null=True, upload_to='aracresimleri'),
        ),
        migrations.AlterField(
            model_name='stoklar',
            name='ruhsat_resimleri',
            field=models.ImageField(blank=True, null=True, upload_to='ruhsatresimleri'),
        ),
    ]
