# Generated by Django 2.2.4 on 2019-12-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191204_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoklar',
            name='arac_resimleri',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stoklar',
            name='ruhsat_resimleri',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
