# Generated by Django 2.2.4 on 2019-12-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191204_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aracresimleri',
            name='added_by',
        ),
        migrations.AddField(
            model_name='aracresimleri',
            name='stoklar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aracresimleri', to='api.Stoklar'),
            preserve_default=False,
        ),
    ]
