# Generated by Django 2.2.4 on 2019-12-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191204_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoklar',
            name='arac_resimleri',
        ),
        migrations.RemoveField(
            model_name='stoklar',
            name='ruhsat_resimleri',
        ),
        migrations.AlterField(
            model_name='aracresimleri',
            name='stoklar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aracresimleri', to='api.Stoklar'),
        ),
    ]
