# Generated by Django 2.2.8 on 2019-12-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191204_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuhsatResimleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ruhsatresimleri')),
                ('stoklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruhsatresimleri', to='api.Stoklar')),
            ],
        ),
    ]
