# Generated by Django 2.2.3 on 2019-12-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cariekle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('vergidairesi', models.CharField(max_length=255, null=True)),
                ('vergino', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('telno', models.CharField(max_length=13, null=True)),
                ('adres', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
