# Generated by Django 2.2.3 on 2019-12-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariekle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cariekle',
            name='telno',
        ),
        migrations.RemoveField(
            model_name='cariekle',
            name='vergidairesi',
        ),
        migrations.RemoveField(
            model_name='cariekle',
            name='vergino',
        ),
        migrations.AddField(
            model_name='cariekle',
            name='tel_no',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='cariekle',
            name='vergi_dairesi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cariekle',
            name='vergi_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cariekle',
            name='adres',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cariekle',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
