# Generated by Django 2.2.3 on 2019-12-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariekle', '0003_auto_20191201_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cariekle',
            name='posta_kodu',
            field=models.IntegerField(blank=True),
        ),
    ]
